SOURCES+=$(SDK_DIR)TOSHIBA.TZ10xx_DFP/Device/Source/system_TZ10xx.c

INCLUDE+=-I$(SDK_DIR)TOSHIBA.TZ10xx_DFP/Device/Include

## Drivers
#SOURCES+=$(SDK_DIR)TOSHIBA.TZ10xx_DFP/RTE_Driver/ACCEL_GYRO_TZ10xx.c
#SOURCES+=$(SDK_DIR)TOSHIBA.TZ10xx_DFP/RTE_Driver/ACCEL_TZ10xx.c
#SOURCES+=$(SDK_DIR)TOSHIBA.TZ10xx_DFP/RTE_Driver/ADCC12_TZ10xx.c
#SOURCES+=$(SDK_DIR)TOSHIBA.TZ10xx_DFP/RTE_Driver/ADCC24_TZ10xx.c
SOURCES+=$(SDK_DIR)TOSHIBA.TZ10xx_DFP/RTE_Driver/ADVTMR_TZ10xx.c
SOURCES+=$(SDK_DIR)TOSHIBA.TZ10xx_DFP/RTE_Driver/GPIO_TZ10xx.c
#SOURCES+=$(SDK_DIR)TOSHIBA.TZ10xx_DFP/RTE_Driver/GYRO_TZ10xx.c
SOURCES+=$(SDK_DIR)TOSHIBA.TZ10xx_DFP/RTE_Driver/I2C_TZ10xx.c
#SOURCES+=$(SDK_DIR)TOSHIBA.TZ10xx_DFP/RTE_Driver/MAG_TZ10xx.c
#SOURCES+=$(SDK_DIR)TOSHIBA.TZ10xx_DFP/RTE_Driver/NOR_TZ10xx.c
SOURCES+=$(SDK_DIR)TOSHIBA.TZ10xx_DFP/RTE_Driver/PMU_TZ10xx.c
SOURCES+=$(SDK_DIR)TOSHIBA.TZ10xx_DFP/RTE_Driver/RNG_TZ10xx.c
#SOURCES+=$(SDK_DIR)TOSHIBA.TZ10xx_DFP/RTE_Driver/RTC_TZ10xx.c
#SOURCES+=$(SDK_DIR)TOSHIBA.TZ10xx_DFP/RTE_Driver/SDMAC_TZ10xx.c
SOURCES+=$(SDK_DIR)TOSHIBA.TZ10xx_DFP/RTE_Driver/SPI_TZ10xx.c
#SOURCES+=$(SDK_DIR)TOSHIBA.TZ10xx_DFP/RTE_Driver/SRAMC_TZ10xx.c
SOURCES+=$(SDK_DIR)TOSHIBA.TZ10xx_DFP/RTE_Driver/TMR_TZ10xx.c
SOURCES+=$(SDK_DIR)TOSHIBA.TZ10xx_DFP/RTE_Driver/UART_TZ10xx.c
#SOURCES+=$(SDK_DIR)TOSHIBA.TZ10xx_DFP/RTE_Driver/USBD_TZ10xx.c
#SOURCES+=$(SDK_DIR)TOSHIBA.TZ10xx_DFP/RTE_Driver/WDT_TZ10xx.c

INCLUDE+=-I$(SDK_DIR)TOSHIBA.TZ10xx_DFP/RTE_Driver

#Middleware
SOURCES+=$(SDK_DIR)TOSHIBA.TZ10xx_DFP/Middleware/TWiC/twic_hash.c
SOURCES+=$(SDK_DIR)TOSHIBA.TZ10xx_DFP/Middleware/TWiC/twic_interface.c
SOURCES+=$(SDK_DIR)TOSHIBA.TZ10xx_DFP/Middleware/TWiC/twic_service.c
SOURCES+=$(SDK_DIR)TOSHIBA.TZ10xx_DFP/Middleware/TWiC/tz1em.c
SOURCES+=$(SDK_DIR)TOSHIBA.TZ10xx_DFP/Middleware/TWiC/tz1em_service.c
SOURCES+=$(SDK_DIR)TOSHIBA.TZ10xx_DFP/Middleware/blelib/blelib.c
SOURCES+=$(SDK_DIR)TOSHIBA.TZ10xx_DFP/Middleware/blelib/blelib_callback.c
SOURCES+=$(SDK_DIR)TOSHIBA.TZ10xx_DFP/Middleware/blelib/blelib_peripheral_statemachine.c


INCLUDE+=-I$(SDK_DIR)TOSHIBA.TZ10xx_DFP/Middleware/TWiC
INCLUDE+=-I$(SDK_DIR)TOSHIBA.TZ10xx_DFP/Middleware/blelib
INCLUDE+=-I$(SDK_DIR)TOSHIBA.TZ10xx_DFP/Middleware/blelib/Config
